import CloseIcon from '@/assets/images/wallets/close.svg';
import { FC } from 'react';
import { createPortal } from 'react-dom';

const TermsModal: FC<{
  open: boolean;
  onClose: () => void;
}> = ({ open, onClose }) => {
  return createPortal(
    <dialog open={open} className="modal bg-black/50">
      <div className="modal-box w-[90vw] lg:w-[440px] max-w-[440px] p-6 bg-[#121212] rounded-[20px]">
        <button
          className="btn btn-xs btn-circle btn-ghost absolute right-6 top-6"
          onClick={onClose}
        >
          <CloseIcon />
        </button>
        <div className="flex flex-col gap-4">
          <div className="text-center text-lg font-bold leading-tight text-yellow">
            Terms And Conditions
          </div>

          <div className="text-sm text-white/80 leading-5 tracking-tight max-w-prose whitespace-pre-wrap break-words max-h-[calc(100vh-243px)] overflow-scroll">
            <h3 className="text-lg text-center">
              $HOLO AIRDROP PROGRAMME TERMS AND CONDITIONS
            </h3>
            {`
Welcome to the $HOLO token airdrop programme (the “Airdrop Programme”), organised and operated by Orbit Technologies Limited (the “Company”, “we”, “our” or “us”). 

These $HOLO Airdrop Terms and Conditions (“Airdrop Terms”) govern your participation in and, where eligible and applicable, receipt of $HOLO tokens (the “Tokens”) through the Airdrop Programme, and supplement the Terms of Use applicable to the Holoworld Foundation’s (the “Foundation”) website which is accessible at [docs.holoworld.com/guidelines/terms-of-service] (“General Terms”). Kindly ensure that you refer to [claim.holoworld.com] as the official website made available by us for the purposes of the Airdrop Programme (the “Airdrop Site”). 

For avoidance of doubt, the Airdrop Programme is organised and operated by the Company, and not the Foundation. The Company (and not the Foundation) shall be responsible for matters relating to the Airdrop Programme.

BY PARTICIPATING IN THE AIRDROP PROGRAMME, INCLUDING BUT NOT LIMITED TO BY ENTERING OR CONNECTING A DIGITAL ASSET WALLET (“DIGITAL WALLET”) AND REGISTERING OR LOGGING IN TO YOUR HOLOWORLD ID (“USER ACCOUNT”) AND, WHERE ELIGIBLE, CLAIMING THE $HOLO TOKENS ON THROUGH THE AIRDROP SITE, PURSUANT TO THE TERMS AND PROCESSES DESCRIBED HEREIN, THE PARTICIPANT (WHETHER AS AN INDIVIDUAL OR AS AN AUTHORISED REPRESENTATIVE OF AN ENTITY):
ACKNOWLEDGES THAT THE PARTICIPANT HAS READ, UNDERSTOOD, AND AGREED TO THESE AIRDROP TERMS IN THEIR ENTIRETY. THE PARTICIPANT IS RESPONSIBLE FOR MAKING ITS OWN DECISION IN RESPECT OF ITS PARTICIPATION IN THE PROGRAMME AND ANY RECEIPT OF TOKENS. ANY PARTICIPATION IN THE PROGRAMME IS SOLELY AT THE PARTICIPANT’S OWN RISK AND IT IS THE PARTICIPANT’S SOLE RESPONSIBILITY TO SEEK APPROPRIATE PROFESSIONAL, LEGAL, FINANCIAL, TAX, AND OTHER ADVICE IN RESPECT OF THE AIRDROP PROGRAMME AND ANY RECEIPT OF THE TOKENS PRIOR TO PARTICIPATING IN THE AIRDROP PROGRAMME AND PRIOR TO RECEIVING ANY TOKENS. 

EXPRESSLY ACKNOWLEDGES AND ASSUMES ALL RISKS RELATED THERETO, INCLUDING (WITHOUT LIMITATION) THE RISKS SET OUT BELOW. IN NO EVENT SHALL THE COMPANY OR ANY PERSON REPRESENTING THE COMPANY BE HELD LIABLE IN CONNECTION WITH OR FOR ANY CLAIMS, LOSSES, DAMAGES, OR OTHER LIABILITIES, WHETHER IN CONTRACT, TORT, OR OTHERWISE, ARISING OUT OF OR IN CONNECTION WITH THE AIRDROP PROGRAMME OR THE RECEIPT OF ANY TOKENS.
THE COMPANY DOES NOT TAKE ANY RESPONSIBILITY FOR THE PARTICIPATION BY ANY PARTICIPANT IN THE AIRDROP PROGRAMME AND SO EACH PARTICIPANT MUST SATISFY ITSELF IN RESPECT OF ANY DUE DILIGENCE OR RISK ASSESSMENTS BEFORE PARTICIPATING IN THE AIRDROP PROGRAMME AND SHOULD NOT RELY ON ANY STATEMENTS OR INFORMATION PROVIDED BY THE COMPANY. THE COMPANY DOES NOT PROVIDE ANY RECOMMENDATION OR ADVICE IN RESPECT OF THE AIRDROP PROGRAMME OR THE TOKENS. THE COMPANY HAS NOT ASSESSED THE SUITABILITY OF THE TOKENS FOR ANY PARTICIPANT. THE COMPANY HAS NOT CONSIDERED THE APPLICABLE LAWS, REGULATIONS AND LAWS OF THE JURISDICTION OF ANY PARTICIPANT. EACH PARTICIPANT PARTICIPATES IN THE AIRDROP PROGRAMME AND RECEIVES TOKENS AT ITS OWN RISK. 
IF YOU DO NOT UNDERSTAND OR ACCEPT ANY TERM SET OUT HEREIN, YOU SHALL NOT PARTICIPATE IN THIS AIRDROP PROGRAMME.

Acceptance of terms

Any capitalised terms that are not defined herein shall have the same meaning as set forth in the General Terms. By accessing and using the Airdrop Site and participating in the Airdrop Programme: 
You agree to abide by these Airdrop Terms and our General Terms, including all terms as may be modified from time to time. In the event of any inconsistency or conflict between the terms and conditions set out in these Terms and any such modified or additional terms and conditions, the latter shall prevail to the extent of such inconsistency or conflict.
You acknowledge and accept all related risks, including without limitation, the risks as set forth herein. We will not be liable to you or any other person for any direct, indirect, special or consequential losses, damages or costs by reason of, or arising from, or as a consequence of, your participation in the Airdrop Programme. Participation in this Airdrop Programme is solely at your own risk and discretion.
THESE TERMS CONTAINS A BINDING INDIVIDUAL ARBITRATION AGREEMENT AND CLASS ACTION WAIVER IN THE SECTION TITLED “DISPUTE RESOLUTION.” THIS AFFECTS YOUR RIGHTS WITH RESPECT TO ANY “DISPUTE” BETWEEN YOU AND THE COMPANY AND MAY REQUIRE YOU TO RESOLVE DISPUTES IN BINDING, INDIVIDUAL ARBITRATION, AND NOT IN COURT. PLEASE READ THIS ENTIRE SET OF TERMS CAREFULLY.

Eligibility

Representations and Warranties. By accessing and/or participating in our Airdrop Programme, you must be and hereby affirm that you: 

are not prohibited or restricted from participating in this Airdrop Programme by any laws or regulations applicable to you;
are an adult of the legal age of majority in your country or state of residence (whichever is higher). If you are under the legal age of majority, you may not access and use the Airdrop Site or participate in this Airdrop Programme; and
are not: 
residing, domiciled or incorporated in any of the Restricted Jurisdictions (defined below); or 
under the control or ownership of a person that is, subject to sanctions or otherwise designated on any list of prohibited or restricted parties, including but not limited to the lists maintained by the United Nations Security Council, the BVI government, the United Kingdom government, the U.S. Government (e.g., the Specially Designated Nationals List and Foreign Sanctions Evaders List of the U.S. Department of Treasury and the Entity List of the U.S. Department of Commerce), the European Union or its Member States, or other applicable government authority,
collectively above, a “Prohibited Person”.

Geographic Restrictions. For the purposes of these Airdrop Terms, “Restricted Jurisdictions” refer to the following jurisdictions:

Iran;
North Korea;
Russia;
Certain regions of Ukraine including Crimea, Sevastopol and the areas of Donetsk, Kherson,
Luhansk and Zaporizhzhia oblasts not controlled by the Ukrainian government;
Cuba;
Yemen;
Sudan;
South Sudan;
Libya;
Lebanon;
Syria; and
any jurisdiction in which participation in the Airdrop Programme would be unlawful, restricted, or where we have opted to limit access as determined by us from time to time. 

You are prohibited from participating in the Airdrop Programme if you are residing, domiciled or incorporated in any of the Restricted Jurisdictions, or if you are accessing the Airdrop Site and the Airdrop Programme from the Restricted Jurisdictions.

Eligible Participants. Tokens will only be airdropped to those participants who fully meet our eligibility requirements (“Eligible Participants”), to be determined by the Company in its sole and absolute discretion. You acknowledge that token distribution is strictly limited to Eligible Participants and we may refuse to distribute any Tokens if you do not qualify as an Eligible Participant, without any liability or further explanation to you.

Eligibility Criteria. The Company, in its sole discretion, shall determine the eligibility criteria for participation in the Airdrop Programme, including the amount of tokens to be distributed to Eligible Participants that satisfy certain criteria. Different Eligible Participants may receive different amounts of Tokens in any particular round of an airdrop (each an “Airdrop Round”), depending on the criteria set forth by the Company for such an instance. The Company may, but shall have no obligation to, notify actual or potential Airdrop Programme participants of the eligibility criteria for any airdrop prior to, during, or after the claims are opened for any Airdrop Round. You accept that we reserve the sole and absolute right to set, adjust, vary, change or waive eligibility criteria based on factors including, but not limited to, regulatory requirements, previous engagement with the Holoworld project and ecosystem, and the range of services and products that we provide (collectively, the “Holoworld Ecosystem”), or other conditions as we may deem relevant.

Verification and Monitoring. We may use IP detection, geo-location services, and other verification tools to monitor and confirm your eligibility and compliance with our eligibility criteria, or to deny you access to the Airdrop Site or Airdrop Programme.

Disqualification. You may be disqualified from the Airdrop Programme and from receiving any tokens from the Airdrop Programme if you are found attempting to bypass any security measure, verification tools or eligibility criteria. The Company reserves the sole and absolute right to disqualify any Eligible Participant or potential participant it deems ineligible for an airdrop (be it under these Airdrop Terms or by having determined that the relevant person engaged in any conduct that the Company considers harmful, unlawful, inappropriate, or unacceptable). Such disqualification may be appropriate if the Company determines, in its sole discretion, for example, that the relevant person may have used multiple addresses to obscure its identity or location or to attempt to game, cheat, or hack the airdrop, Tokens, or the protocol.

Right to Maintain Confidentiality. We may withhold eligibility information to protect the integrity of the Airdrop Programme, ensure compliance, or prevent manipulation. We are not required to explain or disclose these criteria, either in part or in full, to you or the public.

Final and Binding Decision. Our decisions in respect of your eligibility for the Airdrop Programme and to receive any Tokens under this Airdrop Programme are final and binding, and we are not obliged to provide any explanations or entertain any appeals in this regard. 

airdrop process and token allocation 
Airdrop and Claim Period. The process of the airdrop and/or claiming of Tokens period will be decided solely at our discretion which may be announced through our official channels. Airdrops may be conducted multiple times or only once, as determined by the Company at its sole and absolute discretion. The Company may adopt different, similar, or identical eligibility criteria or participation requirements as the Company determines at its sole and absolute discretion. Successful participation in a prior Airdrop Round does not guarantee, nor shall it create an expectation of, participation in a subsequent Airdrop Round. We reserve the right to modify, extend, or cancel the Airdrop Programme or any Airdrop Round at any time without prior notice to you. 

Eligibility Verification. You are required to follow our required steps to verify your eligibility, which may include providing or connecting a compatible Digital Wallet and/or registering or logging in with your User Account, before you may be qualified to receive Tokens through this Airdrop.

Claiming Tokens. Eligible Participants will be required to follow the claim process within the designated claim period. This may involve connecting a compatible Digital Wallet and/or registering or logging in with your User Account, confirming your identity (whether through any know-your-customer (KYC processes) or through any other verification process that we may implement), or completing any additional steps as we may deem necessary. Failure to claim Tokens within the stated period may result in forfeiture, and we are under no obligation to provide extensions or reissue any unclaimed Tokens to you. In addition, the Company may introduce tiered claiming periods or implement various measures to incentivize the staking of the Tokens or to encourage participants to claim the Tokens only after a minimum period has elapsed, such as proportionate allocation reduction mechanisms. For example, you may forfeit a portion of your Tokens allocation and receive less Tokens if you opt to unlock and claim and receive your Tokens at a shorter timeframe compared to other airdrop participants. Correspondingly, airdrop participants who opt to claim and receive their Tokens at a later date may be entitled to a greater portion of their Tokens allocation or additional rewards at the sole discretion of the Company. Kindly refer to the Airdrop Site for more details on the process for claiming Tokens. 

The Company will not be responsible or liable for any loss, non-delivery or forfeiture of Tokens or ineligibility of a participant arising from the participant’s failure to comply with or follow the relevant claims process established by the Company. When you link or connect your Digital Wallet to the Airdrop Site, your use of your Digital Wallet is at your own risk, and subject to the relevant Digital Wallet’s service provider’s terms and conditions.

Transaction Fees. You are responsible for any transaction fees, including gas fees, that may be required to claim or transfer Tokens. You will not be able to claim or transfer your Tokens if the necessary gas fees have not been paid. Such transaction fees (including gas fees) often fluctuate based on a number of factors, all of which are not under our control, and may therefore change at any time without notice.

Token Allocation. We reserve the sole and absolute right to determine the total number of Tokens to be distributed in the Airdrop. Your participation in the Airdrop does not guarantee receipt of a specific number of tokens. Allocation amounts may vary among Eligible Participants, and we make no representation or warranty as to the quantity of Tokens any Eligible Participant may receive. Additionally, the Company may, at any time, make adjustments or variations (such as an increase or decrease) to the Tokens that participants are entitled to receive (whether as part of a points reconciliation exercise or proportional allocation adjustments mechanisms as part of the airdrop claims process).

No Guarantee of Token Value. The Tokens distributed through this Airdrop Programme are provided on an “as-is” basis. We make no representations or warranties regarding the future value, liquidity, functionality, or utility of the Tokens.

Use of Digital Wallet.  Participants hereby agree and confirm that it is the legal owner of the relevant Digital Wallet address that it provides for the purposes of the Airdrop Programme and will not sell, assign, or transfer control of such address or the Tokens to third parties to circumvent any Transferability Restrictions (as defined below) or to knowingly redistribute Tokens to any third party that would violate these Airdrop Terms if claimed directly by such third party. By linking or using a Digital Wallet, the participant agrees that it is using the Digital Wallet in accordance with the applicable terms and conditions of the relevant third-party provider of such Digital Wallet. Each participant acknowledges and agrees that the Digital Wallet is not maintained or supported by, or associated or affiliated with, the Company, and that the Company has no control over the Digital Wallet or the provision of services relating thereto. When a participant interacts with any website or application for the Airdrop Programme (including the Airdrop Site), as between the Company and the relevant participant, the participant retains control over any tokens, cryptocurrencies and other crypto or blockchain-based digital assets (collectively, "Digital Assets") held in the participant’s Digital Wallet at all times. The Company does not control the Digital Assets, including the Tokens, in a participant’s Digital Wallet, and the Company accepts no responsibility or liability to any participant in connection with that participant’s use of a Digital Wallet. The Company makes no representations or warranties regarding how the Airdrop Site, Airdrop Programme or any website or application relating thereto will operate with, or be compatible with, any specific Digital Wallet. The private keys necessary to access and/or transfer the Digital Assets held in a Digital Wallet are not known or held by the Company. Any third party that has or may gain access to a participant’s login credentials, private key, or third-party cloud or storage mechanism for such information may be able to misappropriate the Tokens and/or other Digital Assets held by the participant. The Company has no ability to help any participant access or recover its private key and/or seed phrase for its Digital Wallet. As between the participant and the Company, the participant is solely responsible for maintaining the confidentiality and security of its private key and Digital Wallet, and the participant is solely responsible for any transaction signed with its private key. The Company is not responsible for any loss associated with the participant’s private key, Digital Wallet, vault, or other storage mechanism.

No Guarantee of Airdrop. The organisation and conduct of this Airdrop Programme and these Airdrop Terms shall not be deemed as a guarantee or promise that any Airdrop Round will occur or that any Tokens will be issued or delivered in the course of this Airdrop Programme. For avoidance of doubt, it is possible that no Airdrop Rounds will be conducted, and no Tokens will be issued or delivered, under this Airdrop Programme.

USE OF TOKENS
Token Usage. Participants acknowledge and agree that the Tokens received through the Airdrop Programme may have specific usage limitations, such as utility within a specific platform or ecosystem, and may have no monetary value. 

Transfer Restrictions. The participants acknowledge and agree that the Tokens delivered pursuant to this Airdrop Programme may be subject to such lock-up periods, vesting schedules or similar restrictions relating to the transfer or disposal of the Tokens (collectively, “Transferability Restrictions”) as determined and imposed by the Company from time to time at its sole and absolute discretion, and the Eligible Participants hereby agree to abide and comply fully with such Transferability Restrictions as a condition to being eligible to claim and receive any Tokens under the Airdrop Programme. Kindly refer to the Airdrop Site for more details on the Transferability Restrictions applicable to the Tokens and Airdrop Round.

Not an Investment Product. Tokens received through the Airdrop Programme are not intended as investment products nor as securities, and each participant acknowledges that the value of the Tokens (if any) may fluctuate and that no guarantees are made regarding future value of the Tokens (if any). The prices of such digital or blockchain assets are extremely volatile, subjective and do not have any inherent or intrinsic value. Fluctuations in the price of other Digital Assets could materially and adversely affect the Tokens, which may also be subject to significant price volatility. In addition, a lack of use or public interest in the Tokens could negatively impact the potential utility or value of the Token. Each Token has no inherent or intrinsic value, as their value is inherently subjective and factors occurring outside of the Company’s control may materially impact the value and desirability of the Tokens. 

No Promise of Usability. The organisation and conduct of this Airdrop Programme, any Airdrop Round and the delivery of Tokens thereto to participants does not constitute, and shall not be deemed as, a promise by the Company that the Tokens are usable, tradeable or provided for any purpose whatsoever, whether immediately after the relevant Airdrop Round or any time thereafter. Each participant hereby acknowledges and agrees that the Tokens received via an Airdrop Round may not have an inherent value, usage or purpose, and that participants have no expectation of profit, value or use in the Tokens.

prohibited activity 
Participants in the Airdrop Programme are strictly prohibited from engaging in any of the following activities. We reserve the right to disqualify you from accessing and using the Airdrop Site and/or participating in the Airdrop Programme and/or pursue legal actions against you if you are found to have engaged in such prohibited activities. 

Circumvention of Eligibility Criteria / Security Measures / Verification Tools. Attempting to bypass geographic, legal, or eligibility restrictions through the use of VPNs, proxies, multiple accounts, or any other means to misrepresent your location or identity.
Fraudulent and Deceptive Practices. Engaging in fraudulent activities, including but not limited to creating fake identities, providing false or misleading information (whether through social media channels or otherwise), or using automated systems or bots to manipulate the airdrop process.
Hacking or Unauthorised Access. Attempting to hack, interfere with, or gain unauthorised access to our systems, smart contracts, or any part of the Airdrop Site or Airdrop Programme infrastructure.
Exploitation and Manipulation. Exploiting any bugs, vulnerabilities, or loopholes in the Airdrop Programme system, including smart contract issues, to gain unfair advantage, acquire additional Tokens, or manipulate the Token distribution. Prohibited activities, include, without limitation:
using multi-accounts and/or multi-wallets;
attempting to cheat or hack the Airdrop Programme systems or the Tokens;
carry out any kind of botting, spamming, sybiling or other forms of automation or other similar forms of conduct; or
Impersonation and Phishing. Impersonating us, our employees, or other participants, or engaging in phishing schemes, including the creation of fake or misleading websites to deceive others or gain unauthorised access to their accounts, wallets or tokens.
Unlawful Activity. Using the Airdrop Site, Airdrop Programme or Tokens for any unlawful purposes, including but not limited to money laundering, financing terrorism, or engaging in sanctioned activities.
Other Offensive Behaviour. Behaving in a manner that the Company deems offensive, inappropriate or illegal. Any such behaviour may result in all of a participant’s Digital Wallets, accounts or addresses being permanently banned from the Airdrop Programme.

By accessing and using the Airdrop Site and participating in the Airdrop Programme, you agree to abide by these Airdrop Terms and acknowledge that we may monitor you for prohibited activities and enforce this prohibition without liability to you.

Information or communication about the airdrop 
Official Source Only. We will announce the details of the Airdrop Programme, and any Airdrop Round, including the official claim process, on our Airdrop Site and/or verified official sites or social media channels. Any claim links or information from unofficial sources should be regarded as fraudulent and ignored. 

Information relating to the Airdrop. You may be able to check your eligibility and other information relating to your Tokens allocation (where applicable) by connecting your eligible Digital Wallet or logging into your User Account on the Airdrop Site. Any results or information provided through such a process (the “Airdrop Information”) is provided for your convenience only, and any results or information provided therein, including information relating to your eligibility and/or Token allocation, is an estimate only, and shall not be binding on the Company. Any Airdrop Information presented to you via the Airdrop Site is not intended to, and shall not, create any expectation on you in respect of your eligibility to receive any Tokens under this Airdrop Programme. No representation or warranty, express or implied, is made as to the fairness, accuracy, timeliness, correctness or completeness of any Airdrop Information provided on the Airdrop Site, and no reliance should be placed on it.  The Airdrop Information is provided solely to assist in assessing your preliminary eligibility for the Airdrop Programme for your convenience only. Results displayed as part of the Airdrop Information do not guarantee final eligibility, participation, or any right to receive tokens or rewards (or the amount thereof). We reserve the right to disqualify participants who are suspected of fraudulent or illegal activities, bypassing eligibility checks, or failing to meet any eligibility criteria. We reserve the right to change our decisions (and accordingly, any Airdrop Information displayed on the Airdrop Site) on or prior to the occurrence of the Airdrop. The final number of Tokens that you may receive (if any) may differ from the results displayed as part of the Airdrop Information. Certain features of the Airdrop Site may require you to log in with your User Account and/or to connect your Digital Wallet in order to access or use such features. When you log in with your User Account and/or connect your Digital Wallet, you do so subject to the terms and conditions imposed by the relevant service provider of the User Account or Digital Wallet, and strictly at your own risk. We will not and cannot be liable or responsible for any loss, damage, injury, expense, liability, cost or fee suffered or incurred by you or any third party in the course of you connecting your Digital Wallet to, and/or logging in to your User Account on, the Airdrop Site.

Non-Binding Nature of Past Communications. Any statements, announcements or information we may have previously made relating to the Airdrop Programme, any Airdrop Round or any Tokens (whether via the Airdrop Site or anywhere else) are not binding and do not constitute a representation or guarantee. We are not liable for any reliance on such past communications. Any information or communication provided by the Company (whether via the Airdrop Site or otherwise) relating to any Token allocation shall not be deemed as, nor shall it create, any expectation, promise or guarantee of any allocation to any Tokens, or any other form of incentives, benefits or rewards.

Third-Party Information. We are not liable for any information or other communication made by any third party relating to the Airdrop Site, Airdrop Programme, any Airdrop Round or any Tokens, including any speculative information about our eligibility criteria or the period of any Airdrop Round or the Airdrop Programme. 

Personal Security. It is your sole responsibility to verify the authenticity of any website, link, or communication claiming to be from us. You are advised to exercise caution when clicking on links, connecting wallets, or sharing any personal information.

No Recovery or Liability. We will not be able to, nor are we obliged to, recover any Tokens or other Digital Assets lost due to scams, phishing attempts, or unauthorised third-party activities. We will not be liable for any losses, damages, or claims arising from your interaction with scam websites, fraudulent links, phishing emails, or any other form of unauthorised third-party activity impersonating us, the Airdrop Site or the Airdrop Programme.


SPECIFIC RISK DISCLOSURES AND DISCLAIMERS
By accessing and using the Airdrop Site and/or by participating in this Airdrop Programme, you acknowledge and accept the following inherent risks associated with Digital Assets, blockchain technology, and participation in the Airdrop Programme. You assume full responsibility for understanding and managing these risks, and you agree that we are not liable for any direct, indirect, special or consequential losses, damages or costs by reason of, or arising from, or as a consequence of, your participation in the Airdrop Programme.
Volatility. Digital Assets are highly volatile and subject to unpredictable fluctuations. Tokens received through this Airdrop Programme may experience extreme price changes, or may lose all value entirely. You should only participate if you are prepared for the possibility that the Tokens received may have limited or no financial value. You acknowledge and agree that such Digital Assets, blockchain technologies and associated assets are highly volatile due to many factors including but not limited to popularity, adoption, speculation, regulation, technology and security risks. You also acknowledge and agree that the cost of transacting on such technologies is variable and may increase at any time causing impact to any activities taking place on the Holoworld Ecosystem. The Company does not invite or make any offer to acquire, purchase, sell, transfer or otherwise deal in any Digital Asset. Third parties may provide services involving the acquisition, purchase, sale, transfer or exchange of Digital Assets; the Company does not provide any such service and does not undertake any liability in connection thereto. You acknowledge and agree these risks and represent that the Company cannot be held liable for changes and fluctuations in value or increased costs.

Technical Risks. Transactions on blockchain networks are irreversible, and Tokens may be lost permanently due to errors, forgotten private keys, or unauthorised access. By participating in the Airdrop Programme, you accept the technical risks associated with blockchain transactions, including delays, errors, and malfunctions that may affect token distribution or access to our Airdrop Site. There are risks associated with using an Internet-based currency, including, but not limited to, the risk of hardware, software and Internet connections failure or problems, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your Digital Wallet. You accept and acknowledge that the Company, nor any other entity within, participating in or associated with the Holoworld Ecosystem, will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when participating in the Airdrop Programme, using the Airdrop Site, the Airdrop Information, the Content, the Holoworld Ecosystem or other applicable blockchain for processing transactions, however caused.

Smart Contract Vulnerabilities. This Airdrop Programme relies on smart contracts, which are potentially vulnerable to security flaws, bugs, and exploits. Any malfunction, coding error, or exploitation of smart contracts could result in partial or complete loss of Tokens. You acknowledge and agree that blockchain and decentralized technologies are an emerging technology and progressing field. Advances in code cracking or technical advances such as the development of quantum computers may present risks to smart contracts, Digital Assets, the Airdrop Site, the Tokens, and the Content which could result in the theft or loss of your cryptographic tokens or property, among other potential consequences. By using the Airdrop Site and any of the Content found therein, and participating in the Airdrop Programme, you acknowledge and agree to undertake these risks.

Service Disruptions. Blockchain networks, wallet providers, and related third party services may experience downtime, delays, or Airdrop Site due to factors beyond our control. These disruptions may delay or prevent access to our Platform and/or the claiming of Tokens, and we are not liable for losses incurred due to such events.

Security of Personal Wallets. You are solely responsible for securing your Digital Wallet, private keys, seed phrases, and other credentials. Loss or theft of your private key may result in permanent loss of Tokens and/or your Digital Assets, and we will not, nor shall we be obliged to, assist in recovery.

Regulatory Restrictions. Digital Assets are subject to evolving legal and regulatory frameworks in multiple jurisdictions. Tokens distributed in this Airdrop Programme may face regulatory restrictions in certain countries, which could limit their use, transferability, or legality. It is your responsibility to understand and comply with applicable laws and regulations in your jurisdiction in respect of the Tokens and the Airdrop Programme.

Tax Obligations. Participation in this Airdrop Programme may have tax implications depending on your jurisdiction. You are solely responsible for determining and fulfilling any tax obligations arising from receiving, holding, or transferring the Tokens. 

Risk of Changes in Functionality. The Tokens do not have any rights, uses, purpose, attributes, functionalities or features, express or implied, and which may change from time to time. 

No inherent or intrinsic value. No promises of future performance or price are or will be made in respect to the Tokens, including no promise of inherent value, no promise of continuing payments, and no guarantee that the Tokens will hold any particular value. Therefore, the recovery of spent resources may be impossible or may be subject to foreign laws or regulations, which may not be the same as the laws in the jurisdiction of the British Virgin Islands or any other applicable jurisdictions.  

Risk of Losing Access to the Tokens Due to Loss of Private Key(s). A private key, or a combination of private keys, is necessary to control and dispose of the Tokens stored in the participant’s Digital Wallet, vault or other storage mechanism. Accordingly, loss of requisite private key(s) associated with the participant’s Digital Wallet, vault or other storage mechanism storing the Tokens may result in loss of such Tokens. Moreover, any third party that gains access to such private key(s), including by gaining access to login credentials of a hosted wallet service used by the Participant, may be able to misappropriate any Tokens held by the participant. The Company cannot be responsible for any such losses.

Risk of Blockchain Level Attacks. As with other decentralized cryptographic tokens based on blockchain technology, the Tokens are or may be susceptible to attacks by nodes or validators responsible for validating/confirming transactions on the relevant blockchain, including, but not limited, to double-spend attacks, majority mining power attacks, and selfish-mining attacks. Any successful attacks present a risk to the Company and the Tokens, including, but not limited to, accurate execution and recording of transactions involving the Tokens.

Risks Associated with Uncertain Regulations and Enforcement Actions. The regulatory status of the Tokens and distributed ledger technology is unclear or unsettled in many jurisdictions, but numerous regulatory authorities across jurisdictions have been outspoken about considering the implementation of regulatory regimes which govern digital asset markets. It is difficult to predict how or whether regulatory agencies may apply existing regulation with respect to such technology and its applications, including the Tokens. It is likewise difficult to predict how or whether legislatures or regulatory agencies may implement changes to law and regulation affecting distributed ledger technology and its applications, including the Tokens. Regulatory actions could negatively impact the Tokens in various ways, including, for purposes of illustration only, through a determination that the Tokens are a regulated financial instrument that requires registration or licensing, or that the Company may not be able to provide regular service in certain areas. The Company may cease operations in a jurisdiction, or even abandon certain features of the project, in the event that regulatory actions, or changes to applicable law or regulation, make it illegal to operate in such jurisdiction, or commercially undesirable to obtain the necessary regulatory approval(s) to operate in such jurisdiction. The Company, the Airdrop Programme, the Airdrop Site and the Tokens may be impacted by one or more regulatory inquiries or regulatory action, which could impede or limit your ability to participate in the Airdrop Programme, your receipt or use of the Tokens and/or your access or use of the Airdrop Site, the Holoworld Ecosystem or other applicable blockchain.

Failure to develop. The Tokens and its associated blockchain protocol are still in the developmental stage, hence there may be large changes to the final design before the official version is released. There is the risk that the development of the Tokens and its associated blockchain protocol will not be executed or implemented as planned, or may not meet any expectation of purchasers or participants of the Airdrop Programme of the Tokens, for a variety of reasons, including without limitation the event of a decline in the prices of any Digital Assets or the Tokens, unforeseen technical difficulties, and shortage of development funds for activities.

Unanticipated Risks. Cryptographic tokens such as the Tokens are a new and untested technology. In addition to the aforementioned risks, there may be other risks associated with the participant’s participation in the Airdrop Programme and/or receipt, claim, holding and use of the Tokens, including those that the Company cannot anticipate. Such risks may further materialize as unanticipated variations or combinations of the risks discussed in these Airdrop Terms.  

Risks Associated with the Development and Maintenance of the Holoworld Ecosystem. The Holoworld Ecosystem are still under development and may undergo significant changes over time. Although it is intended for the Tokens, Holoworld Ecosystem to follow the roadmap as may be communicated by the Company, and the Company will endeavour to work towards those ends (subject to internal business considerations), changes may be required to be made to the specifications, features, functionality, purpose, plans and/or other details of the Tokens, the Holoworld Ecosystem for any number of reasons. This could create the risk that the Tokens, the Holoworld Ecosystem, as further developed and maintained, may not meet the participant’s expectations or requirements at the time of purchase. Furthermore, despite the Company’s good faith efforts to develop and maintain the Holoworld Ecosystem, it is still possible that the Holoworld Ecosystem will experience malfunctions or otherwise fail to be adequately developed or maintained or fail to be adequately adopted, which may negatively impact the Holoworld Ecosystem and the Tokens. 

Inadequate disclosure of information. As at the date hereof, the Holoworld Ecosystem and the Tokens are still under development and its design concepts, consensus mechanisms, algorithms, codes, and other technical details and parameters may be constantly and frequently updated and changed. Although the Airdrop Site, Airdrop Terms and the documentation available at [docs.holoworld.com] contains the most current information relating to the Holoworld Ecosystem and the Tokens, it is not absolutely complete and may still be adjusted and updated by the team from time to time. The team has no ability and obligation to keep holders of the Tokens informed of every detail (including development progress and expected milestones) regarding the project to develop the Holoworld Ecosystem, hence insufficient information disclosure is inevitable and reasonable.

Risks Related to Corporate Structure. The legal structure for the Company (including the intra-group arrangements) is bespoke and there is no generally accepted standard or structure for similar projects in the distributed ledger technology space. The legal structure had been designed to address certain specific legal risks, and attempt to decentralize the management and control, as well as economic risks and benefits relating to the Holoworld Ecosystem and the Tokens; but there is no legal precedent for whether these structures are effective and it is difficult to predict the position that a regulator may adopt. The legal structure and contractual arrangements may not be effective in decentralizing management and control, thereby adversely affecting the value of Holoworld Ecosystem and/or the Tokens.

Risk of Dissolution of the Company, or any of the Company’s Group entities, the Holoworld Ecosystem. Start-up companies such as the Company involve a high degree of risk. Financial and operating risks confronting start-up companies are significant, and the Company is not immune to these. Start-up companies often experience unexpected problems in the areas of product development, marketing, financing, and general management, among others, which frequently cannot be solved. It is possible that, due to any number of reasons, including, but not limited to, an unfavourable fluctuation in the value of cryptographic and fiat currencies, decrease in the utility of the Tokens due to negative adoption of Holoworld Ecosystem, the failure of commercial relationships, or intellectual property ownership challenges, Holoworld Ecosystem may no longer be viable to operate and the Company may be dissolved.

Risks Arising from Lack of Governance Rights. Because the Tokens confer no governance rights of any kind with respect to the Company, all decisions involving the Company will be made by the Company at its sole and absolute discretion, including, but not limited to, decisions to discontinue the operations or development of the Holoworld Ecosystem, to create, distribute and/or sell more Tokens or other Digital Assets for use within Holoworld Ecosystem, or to sell or liquidate the Company. These decisions could adversely affect Holoworld Ecosystem and the Tokens held by the participant.

Risks Involving Cloud Storage. As the Airdrop Site and the Airdrop Programme may provide or utilize a decentralized cloud storage service for users and applications, therefore the Airdrop Site and the Airdrop Programme are susceptible to a number of risks related to the storage of data in the cloud. The Airdrop Site and the Airdrop Programme may involve the storage of large amounts of sensitive and/or proprietary information, which may be compromised in the event of a cyberattack or other malicious activity. Similarly, the Airdrop Site and the Airdrop Programme may be interrupted and files may become temporarily unavailable in the event of such an attack or malicious activity. Because users can utilize a variety of hardware and software that may interface with the Holoworld Ecosystem, there is the risk that the Airdrop Site and the Airdrop Programme may become unavailable or interrupted based on a failure of interoperability or an inability to integrate these third-party systems and devices that the Company does not control. The risk that the Airdrop Site and the Airdrop Programme may face increasing interruptions and Holoworld Ecosystem may face additional security vulnerabilities could adversely affect Holoworld Ecosystem and therefore the future utility of any Tokens held by the Participant.

Forking. As parts of the Holoworld Ecosystem may contain open-source components, the Company does not and cannot monopolize the development, marketing, operation or otherwise of Holoworld Ecosystem and the underlying blockchain. Any entity may independently develop a patch or upgrade of the source code of the Holoworld Ecosystem and the underlying blockchain (or any part thereof) without prior authorization of any other person, and launch the same by deployment on any underlying blockchain network. The acceptance of these patches or upgrades by a sufficient (not necessarily overwhelming) percentage of the Tokens’ holders could result in a "fork" in the network, and consequently two diverging networks will emerge and remain. Each branch arising from the fork will have its own native cryptographic tokens – accordingly there may be two different versions of the Tokens respectively residing in the two divergent branches with almost identical technical features and functions. The tokens on the diverging network will not be considered as the Tokens.

Further, it is theoretically possible for each branch of the forked blockchain to be further forked an unlimited number of times. The temporary or permanent existence of forked blockchains could adversely affect the operation of Holoworld Ecosystem and underlying blockchain and the Tokens held by the participant, and may ruin the sustainability of Holoworld Ecosystem.

Risks associated with a lack of markets for the Tokens. There is no prior market for the Tokens and the distribution, airdropping or sale of the Tokens may not result in an active or liquid market for the Tokens. The Tokens are designed to be utilized solely within the Holoworld Ecosystem, hence there may be illiquidity risk with respect to the Tokens held by the participant. The Tokens are not a currency issued by any central bank or national, supra-national or quasi-national organization, nor is it backed by any hard assets or other credit nor is it a "commodity" in the usual and traditional sense of that word. The Company is not responsible for, nor does the Company pursue, the circulation and trading of the Tokens on any market. Trading of the Tokens will merely depend on the consensus on its value between the relevant market participants. No one is obliged to purchase any Tokens from any holder of the Tokens, nor does anyone guarantee the liquidity or market price of the Tokens to any extent at any time. Furthermore, the Tokens may not be resold to a purchaser who is a Prohibited Person or to purchasers where the purchase of such Tokens may be in violation of applicable laws. Accordingly, the Company cannot ensure that there will be any demand or market for the Tokens. 

Even if secondary trading of the Tokens is facilitated by third party exchanges, such exchanges may be relatively new and subject to little or no regulatory oversight, making them more susceptible to fraud or manipulation. Furthermore, to the extent that third parties do ascribe an external exchange value to the Tokens (e.g., as denominated in a digital or fiat currency), such value may be extremely volatile and/or diminish to zero. The Company has no oversight nor control over such secondary trading.

Inflation. Due to the nature and operation of blockchain protocols, the total amount of circulating Tokens could increase through the adoption of a new patch or upgrade of the source code. Any inflation in the quantity of the Tokens could adversely affect the market price of the Tokens, and consequently buyers may suffer economic losses. Neither the Company provides any guarantee that a participant would be compensated (in any manner) for such inflation.

Third-Party Providers And Services
The platform for claiming the tokens through this Airdrop Programme may contain software or services provided by or links to third-party services (“Third-Party Content”). We make no warranties or representations, express or implied, in respect of the availability, functionality or content of such Third-Party Content, and you agree that we shall not be liable for any loss or damages arising from or in connection with your use of any third-party services. You may be subject to the terms and policies of such relevant third-parties. 

Data Protection and Privacy
In the course of your access and/or use of the Airdrop Site, or your participation in this Airdrop Programme, we may be required to collect, use, disclose and/or process certain data (including personal data) belonging to you. In this regard, we will collect, use, disclose and/or process your personal data in accordance with applicable data protection and privacy laws, and as set out in our Privacy Policy.

no fiduciary relationship or reliance
Your participation in the Airdrop Programme does not create any fiduciary, advisory, or agency relationship between you and us. We do not act as a fiduciary or advisor to any participant, and no information or communication from us should be interpreted as financial, legal, tax, or other professional advice.

Any decisions you make regarding your participation in the Airdrop Programme are solely at your own risk, and you should not rely on any statements of information from us as a basis for making financial or legal decisions. 

Any and all information provided in connection with your access and use of the Airdrop Site (or any content made available therein), should not and may not be construed as legal, tax, investment, financial, professional or other advice. You should not take, and should refrain from taking, any action based on any information contained on the Airdrop Site (or any content made available thereon), or any other information we make available at any time, including, without limitation, blog posts, articles, links to third-party content, discord or Telegram content, news feeds, tutorials, tweets and videos. Before you make any financial, legal or other decisions involving the Airdrop Site (or any content made available thereon) or use thereof, you should seek independent professional advice (including legal, tax, and financial advisors) from an individual who is licensed and qualified in the area for which such advice would be appropriate (such as to fully understand the implications of receiving and holding Tokens and the potential risks involved). You further agree that the only duties and obligations that we have are expressly set out in these Airdrop Terms.

Limited Warranty and Disclaimer
GENERAL:

TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, THE AIRDROP SITE, AIRDROP PROGRAMME, AIRDROP INFORMATION, THE HOLOWORLD ECOSYSTEM AND THE TOKENS ARE PROVIDED ON AN “AS IS”, “UNDER DEVELOPMENT”, "WITH ALL FAULTS" AND “AS AVAILABLE,” BASIS FOR USE, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF CONDITION, UNINTERRUPTED OR ERROR-FREE USE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, TITLE, AND THOSE ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.

YOU ACKNOWLEDGE AND AGREE THAT YOU ASSUME FULL RESPONSIBILITY FOR YOUR ACCESS AND USE OF THE AIRDROP SITE, ANY AIRDROP INFORMATION, AND YOUR PARTICIPATION IN THE AIRDROP PROGRAMME AND FOR YOUR RECEIPT OF THE TOKENS. YOU ACKNOWLEDGE AND AGREE THAT ANY INFORMATION YOU SEND OR RECEIVE DURING YOUR ACCESS AND USE OF THE AIRDROP SITE AND AIRDROP INFORMATION, AND YOUR PARTICIPATION IN THE AIRDROP PROGRAMME MAY NOT BE SECURE AND MAY BE INTERCEPTED OR LATER ACQUIRED BY UNAUTHORIZED PARTIES. YOU ACKNOWLEDGE AND AGREE THAT YOUR ACCESS AND USE OF THE AIRDROP SITE, AIRDROP INFORMATION AND YOUR PARTICIPATION IN THE AIRDROP PROGRAMME IS AT YOUR OWN RISK. RECOGNIZING SUCH, YOU ACKNOWLEDGE AND AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER THE COMPANY, ITS DIRECTORS, OFFICERS AND EMPLOYEES, NOR ITS SUPPLIERS, THIRD PARTY PARTNERS OR LICENSORS WILL BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY OR OTHER DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER TANGIBLE OR INTANGIBLE LOSSES OR ANY OTHER DAMAGES BASED ON CONTRACT, TORT, STRICT LIABILITY, INFRINGEMENT OF INTELLECTUAL PROPERTY OR THEFT OR MISAPPROPRIATION OF PROPERTY OR ANY OTHER THEORY (EVEN IF THE COMPANY HAD BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM (A) YOUR ACCESS AND USE OF THE AIRDROP SITE, AIRDROP INFORMATION AND YOUR PARTICIPATION IN THE AIRDROP PROGRAMME OR RECEIPT OF THE TOKENS; (B) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (C) STATEMENTS, CONTENT OR CONDUCT OF ANY THIRD PARTY IN THE COURSE OF THE AIRDROP PROGRAMME; (D) ANY ACTIONS THE COMPANY TAKES OR FAILS TO TAKE AS A RESULT OF COMMUNICATIONS YOU SEND; (E) HUMAN ERRORS; (F) TECHNICAL MALFUNCTIONS; (G) FAILURES, INCLUDING PUBLIC UTILITY OR TELEPHONE OUTAGES; (H) OMISSIONS, INTERRUPTIONS, LATENCY, DELETIONS OR DEFECTS OF ANY DEVICE OR NETWORK, PROVIDERS, OR SOFTWARE (INCLUDING, BUT NOT LIMITED TO, THOSE THAT DO NOT PERMIT ACCESS AND USE OF THE AIRDROP SITE OR PARTICIPATION IN THE  AIRDROP PROGRAMME); (I) ANY INJURY OR DAMAGE TO COMPUTER EQUIPMENT; (J) INABILITY TO FULLY ACCESS THE AIRDROP PROGRAMME SYSTEMS; (K) THEFT, TAMPERING, DESTRUCTION, OR UNAUTHORIZED ACCESS TO, IMAGES OR OTHER CONTENT OF ANY KIND; (L) DATA THAT IS PROCESSED LATE OR INCORRECTLY OR IS INCOMPLETE OR LOST; (M) TYPOGRAPHICAL, PRINTING OR OTHER ERRORS, OR ANY COMBINATION THEREOF; (N) FAILURE TO RECEIVE, OR DELAY IN RECEIVING, ANY TOKENS; (O) INELIGIBILITY FOR ANY AIRDROP ROUND; OR (P) ANY OTHER MATTER RELATING TO THE AIRDROP SITE OR AIRDROP PROGRAMME. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.

THE COMPANY, ITS DIRECTORS, OFFICERS AND EMPLOYEES WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU INCUR AS THE RESULT OF YOUR USE OF ANY DIGITAL WALLETS OR OTHER APPLICABLE BLOCKCHAIN, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (A) USER ERROR, SUCH AS FORGOTTEN OR COMPROMISED PASSWORDS OR SEED PHRASES OR INCORRECTLY CONSTRUED SMART CONTRACTS OR OTHER TRANSACTIONS; (B) SERVER FAILURE OR DATA LOSS; (C) CORRUPTED WALLET FILES; (D) INTELLECTUAL PROPERTY INFRINGEMENT BY THE USERS; (E) UNAUTHORIZED ACCESS OR ACTIVITIES BY THIRD PARTIES, INCLUDING BUT NOT LIMITED TO THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE AIRDROP SITE AND ANY FEATURE AND ANY CONTENT MADE AVAILABLE THEREON.

For avoidance of doubt, the Foundation is not a party to these Airdrop Terms, and shall not be responsible for any matters relating to the Tokens, any Airdrop Round, Airdrop Terms, the Airdrop Programme and the Airdrop Site.

Other Specific Disclaimers

You acknowledge and agree that the Airdrop Programme will be conducted via, and the Airdrop Site and the Content made available thereon are provided as, software code and are subject to flaws and acknowledge that you are solely responsible for evaluating any smart contract, code provided by or on the Airdrop Site and/or the Content made available thereon and the trustworthiness of any third-party websites, products, smart-contracts, or content you access or use through the Airdrop Site. Like all software, the conduct of the Airdrop Programme and the access and use of the Airdrop Site and the Content may be subject to exploits. The Company is not and will not be responsible for exploits of any kind. While the Company has taken a number of precautions to maintain the security of the Airdrop Site and the Content (including without limitation, working with the Foundation or other third parties to do the same), this is a nascent technology and it is not possible to guarantee that the software codes or any smart contracts are completely free from vulnerabilities, bugs or errors. You accept all risks that arise from using the Airdrop Site and any of the Content made available thereon, including, and not limited to, the risk of any funds being lost due to a failure or exploit of the Airdrop Programme, the Airdrop Site or any of the Content. You further expressly acknowledge and agree that the Digital Assets, and the Holoworld Ecosystem applications or other blockchain applications can be written maliciously or negligently, that the Company cannot be held liable for your interaction with such Digital Assets applications and that such applications may cause the loss of property or even identity. This warning and others later provided by the Company in no way evidence or represent an on-going duty to alert you to all of the potential risks of utilizing the Website or any Content made available thereon.


Limitations of Liability

To the fullest extent allowed by applicable law, the Company, its parent, subsidiaries, Third Party Providers and affiliates shall not be liable for any loss or damage arising out of your participation in this Airdrop Programme. The liability of the Company to you in connection with this Airdrop Programme shall not, under any circumstances, exceed USD$1, unless applicable law explicitly disallows this limitation, in which case the Company’s liability shall be limited to the fullest extent permitted by applicable law.

Indemnity

You hereby agree to defend and indemnify the Company, its parent, subsidiaries, licensors and affiliates against and from any third party claims, liabilities, losses, injuries, damages, costs or expenses incurred by the Company arising out of or from any violation by you of these Terms.

Equitable Remedies

You agree that the Company would be irreparably damaged if the sections of these Terms were not specifically followed and enforced. In such an event, you agree that the Company shall be entitled, without bond or other security, or proof of damages, to appropriate equitable relief in the event you breach these Terms; and that the awarding of equitable relief to the Company will not limit its ability to receive remedies that are otherwise available to the Company under applicable laws.

General 
Entire Agreement. These Airdrop Terms and the General Terms, including any modifications that we may make from time to time, contain the entire agreement between you and us regarding the Airdrop Programme and supersede all prior communications or agreements between the parties regarding the Airdrop Programme.

Severability. If any term of these Airdrop Terms is or becomes invalid or unenforceable by any legislation to which it is subject to, it shall be deemed deleted to the extent of such invalidity or unenforceability, and it shall in no way affect or prejudice the validity or enforceability of the reminder of such term or the other terms of these Airdrop Terms.

Assignment. None of your rights or duties under these Airdrop Terms may be transferred, assigned or delegated by you without our prior written consent, and any attempted transfer, assignment or delegation without such consent will be void and without effect. We may freely transfer, assign or delegate our rights and duties under these Airdrop Terms. Subject to the foregoing, these Airdrop Terms will be binding upon and will inure to the benefit of the parties and their respective representatives, heirs, administrators, successors and permitted assigns.

Headings. The headings of the sections of these Airdrop Terms are for convenience of reference only and are not intended to restrict, affect or be of any weight in the interpretation or construction of the provisions of such sections.

Waiver. No failure on the part of any Party to exercise and no delay on the part of any Party in exercising any right hereunder will operate as a release or waiver thereof, nor will any single or partial exercise of any right under these Airdrop Terms preclude any other or further exercise of it. 

Dispute Resolution
PLEASE READ THIS SECTION CAREFULLY. IT MAY SIGNIFICANTLY AFFECT YOUR RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT OR TO PURSUE CLAIMS IN A CLASS OR REPRESENTATIVE CAPACITY

Applicability of this Dispute Resolution Policy. This binding individual arbitration section will not apply to the extent prohibited by the laws of your country of residence. To the fullest extent allowed by applicable law, you and the Company agree to submit all Disputes between us to individual, binding arbitration. A “Dispute” means any dispute, claim, or controversy (except those specifically exempted below) between you and the Company that relates to any aspect of our relationship, including, without limitation, your use or attempted use of the Airdrop Site or your participation in the Airdrop Programme , and all marketing related to them, any licensed content, and all matters arising under these Airdrop Terms, the Company’s Privacy Policy, or any other agreement between you and the Company, including the validity and enforceability of this agreement to arbitrate. A Dispute shall be subject to binding, individual arbitration regardless of whether it is based in contract, statute, regulation, ordinance, tort (including fraud, misrepresentation, fraudulent inducement, or negligence), or any other legal or equitable theory. This includes claims that accrued before you entered into these Airdrop Terms. You understand that there is no judge or jury in arbitration and that court review of an arbitration award is limited.

Informal Negotiation Period. In an effort to accelerate resolution and reduce the cost of any Dispute related to, or arising out of, these Airdrop Terms, you and the Company agree to first attempt to negotiate any Dispute (except as set out in Section 13.F. below) informally for at least thirty (30) days before either party initiates any arbitration or court proceeding. Notice must be provided within one (1) year of the Dispute having arisen, but in no event after the date on which the initiation of legal proceedings would have been barred under the applicable statute of limitations. The failure to provide timely notice shall bar all claims.

Negotiations will begin upon receipt of written notice by the party raising the Dispute. The Company will send its notice to your e-mail address or otherwise contact you via the registered telephone number that you have provided to us.
You will send your notice to the Company at [director@orbittechnologieslimited.com].

Binding Arbitration. If a Dispute cannot be resolved through negotiations, either you or the Company may elect to have the Dispute finally and exclusively resolved by binding arbitration. The provision by you of a notice to the Company, containing all of the information referenced above, and your good-faith participation in the Informal Negotiation Period, are prerequisites to commencing arbitration.

Any dispute as to any matter arising under, out of or in connection with this Agreement (including but not limited to any question regarding its existence, validity or termination) shall be referred to and finally and exclusively determined by arbitration in the British Virgin Islands at the International Arbitration Centre of the British Virgin Islands (“BVI IAC”) in accordance with the Arbitration Rules of the BVI IAC for the time being in force, which rules are deemed to be incorporated by reference in this Clause. The Tribunal shall consist of one arbitrator to be appointed by the Chairman (or equivalent position) of the BVI IAC. The language of the arbitration shall be English. The award by the arbitrator shall be valid, final and binding on each of the Parties. The Parties shall have the right to seek interim injunctive relief from a court of competent jurisdiction, both before and after the arbitrator has been appointed, at any time up until the arbitrator has made its final award. The Parties undertake to carry out any award without delay and waive their right to any form of recourse insofar as such waiver can validly be made. Judgment upon the award may be entered by any court having jurisdiction thereof or having jurisdiction over the relevant party or its assets. You and the Company shall be responsible for their respective attorneys’ fees and expenses.

THE ARBITRATION PROCEEDINGS DESCRIBED HEREIN WILL BE CONDUCTED ON AN INDIVIDUAL BASIS ONLY. The arbitrator may not consolidate disputes against the Company by other individuals or entities unless the Company expressly consents to such consolidation. These Airdrop Terms provide no right or authority for any Dispute to be arbitrated, adjudicated, or resolved through proceedings on a class or representative basis or using class action procedures. The arbitrator may award any relief that is permitted by applicable law with respect to your individual claim, but to the maximum extent permitted by applicable law, may not award relief against the Company respecting any person other than you.

Class and Collective Action Waiver. To the fullest extent allowed by applicable law, you and the Company agree that neither you nor the Company may participate as a class representative, private attorney general, or as a member of any class of claimants for any Dispute subject to arbitration or for any non-arbitrable claim pursued in court. The arbitrator and any court shall construe the agreement to arbitrate and the agreement to waive class or collective actions in any manner that will render them enforceable and give them effect. If, for any reason, this class or collective action waiver is deemed unenforceable by a court or arbitrator, you agree that the parties’ contract to arbitrate is then entirely void. If any portion of these Airdrop Terms other than the class action waiver is found illegal or unenforceable, such portion shall be severed and the remainder of these Airdrop Terms shall be given full force and effect. Any Dispute subject to any such portion of these Airdrop Terms shall be decided by the arbitrator.

Governing Law. Unless these Airdrop Terms include express language to the contrary, all Disputes shall be governed by and construed under the laws of the British Virgin Islands without regard to choice of law principles. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. This paragraph will be interpreted as broadly as applicable law permits. 

Exceptions to Negotiations and Arbitration. You and the Company agree that the following Disputes are not subject to the above provisions concerning negotiations and binding arbitration:
any Dispute seeking to enforce or protect, or concerning the validity of, any of the Company’s intellectual property rights;
any Dispute related to, or arising from, claims that the other party has committed piracy;
individual actions duly filed in a small-claims court of competent jurisdiction on a non-representative basis; any claim within the jurisdictional limits of the small claims courts;
enforcement actions pursued through a governmental agency if permitted by applicable law;
the Company’s right to seek injunctive relief to preserve the status quo pending or during an arbitration.  

Claims excluded from arbitration under this section are subject to the choice of law, forum selection, and jury waiver clauses set forth in these Airdrop Terms.

`}
          </div>

          <button
            className="btn col-span-2 rounded-full border-none text-black/95 font-bold text-sm"
            onClick={onClose}
            style={{
              background:
                'linear-gradient(156.17deg, #08EDDF -8.59%, #8FEDA6 73.29%, #CEED8B 104.51%)',
            }}
          >
            Got it
          </button>
        </div>
      </div>
    </dialog>,
    document.body,
  );
};

export default TermsModal;
